# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Michael Tran
author_email: bhklab.jamesbannon@gmail.com
author_full_name: James Bannon
github_username: jbannon
has_additional_authors: true
project_description: Pipeline for computing LINCS signatures from the raw data
project_name: Lincs Pipeline
project_slug: lincs-pipeline
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
