[workspace]
name = "lincs-pipeline"
authors = [
    "James Bannon <bhklab.jamesbannon@gmail.com>",
    "Michael Tran <michaelcao-anh.tran@uhn.ca>",
]
description = "Pipeline for computing LINCS signatures from the raw data"
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]
version = "2.0.0"

[activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.RAW_METADATA = "${PIXI_PROJECT_ROOT}/data/rawdata/metadata"
env.PROC_METADATA = "${PIXI_PROJECT_ROOT}/data/procdata/metadata"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = ">=3.14.4,<3.15"
ipython = "*"
ipykernel = "*"
jupyterlab = "*"
pip = "*"
r-base = ">=4.5,<4.6"
r-httr2 = ">=1.2.2,<2"
r-jsonlite = ">=2.0.0,<3"
r-tibble = ">=3.3.1,<4"
r-arrow = "*"
r-knitr = "*"
r-rmarkdown = "*"
r-yaml = "*"
pandoc = "*"
bioconductor-multiassayexperiment = "*"
bioconductor-summarizedexperiment = "*"
bioconductor-s4vectors = "*"
ruff = "*"
ty = ">=0.0.24,<0.0.25"
r-readr = ">=2.2.0,<3"

[pypi-dependencies]
damply = ">=0.10.0, <0.11"
numpy = ">=2.4.4, <3"
pandas = ">=3.0.2, <4"
cmappy = ">=4.0.1, <5"
scikit-learn = ">=1.8.0, <2"
snakemake = ">=9.6.2, <10"

[tasks]
qc = "Rscript -e \"rmarkdown::render('qc/lincs_qc.Rmd', output_dir = 'qc', knit_root_dir = getwd())\""
